elao_enum:
    doctrine:
        types:
            App\Enum\UserStatus: userstatus
            App\Enum\GroupType: grouptype
            App\Enum\DocumentIdentityTypeEnum: identitydoctype
            App\Enum\AccessType: accesstype
